
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
;=====================================
[exPbx_01]
type=endpoint
transport=transport-udp
context=from-pstn
disallow=all
allow=ulaw
allow=alaw
outbound_auth=exPbx_01
aors=exPbx_01
[exPbx_01]
type=aor
qualify_frequency=60
contact=sip:192.168.192.1:5060
[exPbx_01]
type=identify
endpoint=exPbx_01
match=192.168.192.1:5060
[exPbx_01]
type=auth
auth_type=userpass
username=user
password=1234

;=====================================
[exPbx_02]
type=endpoint
transport=transport-udp
context=from-pstn
disallow=all
allow=ulaw
allow=alaw
outbound_auth=exPbx_02
aors=exPbx_02
[exPbx_02]
type=aor
qualify_frequency=60
contact=sip:192.168.192.2:5060
[exPbx_02]
type=identify
endpoint=exPbx_02
match=192.168.192.2:5060
[exPbx_02]
type=auth
auth_type=userpass
username=user
password=1234

;=====================================
[exPbx_04]
type=endpoint
transport=transport-udp
context=from-pstn
disallow=all
allow=ulaw
allow=alaw
outbound_auth=exPbx_04
aors=exPbx_04
[exPbx_04]
type=aor
qualify_frequency=60
contact=sip:192.168.192.4:5060
[exPbx_04]
type=identify
endpoint=exPbx_04
match=192.168.192.4:5060
[exPbx_04]
type=auth
auth_type=userpass
username=user
password=1234

;=====================================
[exPbx_05]
type=endpoint
transport=transport-udp
context=from-pstn
disallow=all
allow=ulaw
allow=alaw
outbound_auth=exPbx_05
aors=exPbx_05
[exPbx_05]
type=aor
qualify_frequency=60
contact=sip:192.168.192.5:5060
[exPbx_05]
type=identify
endpoint=exPbx_05
match=192.168.192.5:5060
[exPbx_05]
type=auth
auth_type=userpass
username=user
password=1234
