
[general]
[default_user]
type=user
[default_bridge]
type=bridge

[admin_user]
type=user
marked=yes
admin=yes
music_on_hold_when_empty=yes
announce_user_count=no
announce_only_user=no

;ConferenceRoom
;=============================================
[myconf700]
type=bridge

;ConferenceRoom
;=============================================
[myconf701]
type=bridge

;ConferenceRoom
;=============================================
[myconf702]
type=bridge

;ConferenceRoom
;=============================================
[myconf704]
type=bridge

;ConferenceRoom
;=============================================
[myconf705]
type=bridge