
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

;=====================================
[exPbx_01]
type=endpoint
transport=transport-udp
context=exPbx_01_in
disallow=all
allow=speex32
allow=ulaw
allow=alaw
outbound_auth=exPbx_01
aors=exPbx_01
[exPbx_01]
type=aor
qualify_frequency=60
contact=sip:192.168.3.230:5060
[exPbx_01]
type=identify
endpoint=exPbx_01
match=192.168.3.230:5060
[exPbx_01]
type=auth
auth_type=userpass
username=111
password=111

;=====================================
[exPbx_02]
type=endpoint
transport=transport-udp
context=exPbx_02_in
disallow=all
allow=speex32
allow=ulaw
allow=alaw
outbound_auth=exPbx_02
aors=exPbx_02
[exPbx_02]
type=aor
qualify_frequency=60
contact=sip:192.168.0.3:5060
[exPbx_02]
type=identify
endpoint=exPbx_02
match=192.168.0.3:5060
[exPbx_02]
type=auth
auth_type=userpass
username=user
password=1234
