
[channels]
usecallerid=yes
callerid=asreceived
callwaiting=yes
usecallingpres=yes
callwaitingcallerid=yes
threewaycalling=yes
transfer=yes
canpark=yes
cancallforward=yes
callreturn=yes
echocancel=yes
echocancelwhenbridged=yes
group=1
callgroup=1
pickupgroup=1
rxgain=0
txgain=0
hwrxgain=0
hwtxgain=3.0
cidsignalling=dtmf
cidstart=dtmf
busydetect=yes
busycount=3
sendcalleridafter =1
context=public


[phone1]
dahdichan=1
context=from-dahdi

[phone2]
dahdichan=2
context=from-dahdi

[phone3]
dahdichan=3
context=from-dahdi

[phone4]
dahdichan=4
context=from-dahdi

[phone5]
dahdichan=5
context=from-dahdi

[phone6]
dahdichan=6
context=from-dahdi

[phone7]
dahdichan=7
context=from-dahdi

[phone8]
dahdichan=8
context=from-dahdi