
[general]
bandwidth=low
disallow=lpc10
jitterbuffer=no
encryption=yes
autokill=yes

[guest]
type=user
context=public
callerid="Guest IAX User"

[iaxtel]
type=user
context=default
auth=rsa
inkeys=iaxtel

[iaxfwd]
type=user
context=default
auth=rsa
inkeys=freeworlddialup

[pbxin]
type=user

[fxsPbx_1]
host=192.168.191.35
type=peer
qualify=yes
context=from-pstn

[fxoPbx_0]
host=192.168.191.4
type=peer
qualify=yes
context=from-pstn

[fxoPbx_1]
host=192.168.191.34
type=peer
qualify=yes
context=from-pstn

[fxsPbx_0]
host=192.168.191.5
type=peer
qualify=yes
context=from-pstn

[t1sPbx_1]
host=192.168.191.33
type=peer
qualify=yes
context=from-pstn

[t1sPbx_0]
host=192.168.191.3
type=peer
qualify=yes
context=from-pstn

[magPbx_1]
host=192.168.191.38
type=peer
qualify=yes
context=from-pstn

[sipPbx_0]
host=192.168.191.2
type=peer
qualify=yes
context=from-pstn

[sipPbx_1]
host=192.168.191.32
type=peer
qualify=yes
context=from-pstn

[magPbx_0]
host=192.168.191.8
type=peer
qualify=yes
context=from-pstn