
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
;=====================================
[190]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=190
aors=190
[190]
type=auth
auth_type=userpass
password=123456789
username=190
[190]
type=aor
max_contacts=1

;=====================================
[191]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=191
aors=191
[191]
type=auth
auth_type=userpass
password=123456789
username=191
[191]
type=aor
max_contacts=1

;=====================================
[192]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=192
aors=192
[192]
type=auth
auth_type=userpass
password=123456789
username=192
[192]
type=aor
max_contacts=1

;=====================================
[193]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=193
aors=193
[193]
type=auth
auth_type=userpass
password=123456789
username=193
[193]
type=aor
max_contacts=1

;=====================================
[194]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=194
aors=194
[194]
type=auth
auth_type=userpass
password=123456789
username=194
[194]
type=aor
max_contacts=1

;=====================================
[195]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=195
aors=195
[195]
type=auth
auth_type=userpass
password=123456789
username=195
[195]
type=aor
max_contacts=1

;=====================================
[120]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=120
aors=120
[120]
type=auth
auth_type=userpass
password=123456789
username=120
[120]
type=aor
max_contacts=1

;=====================================
[121]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=121
aors=121
[121]
type=auth
auth_type=userpass
password=123456789
username=121
[121]
type=aor
max_contacts=1

;=====================================
[122]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=122
aors=122
[122]
type=auth
auth_type=userpass
password=123456789
username=122
[122]
type=aor
max_contacts=1

;=====================================
[102]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=102
aors=102
[102]
type=auth
auth_type=userpass
password=123456789
username=102
[102]
type=aor
max_contacts=1

;=====================================
[104]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=104
aors=104
[104]
type=auth
auth_type=userpass
password=123456789
username=104
[104]
type=aor
max_contacts=1

;=====================================
[106]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=106
aors=106
[106]
type=auth
auth_type=userpass
password=123456789
username=106
[106]
type=aor
max_contacts=1

;=====================================
[108]
type=endpoint
context=from-pstn
disallow=all
allow=ulaw
transport=transport-udp
auth=108
aors=108
[108]
type=auth
auth_type=userpass
password=123456789
username=108
[108]
type=aor
max_contacts=1
