
[channels]
usecallerid=yes
callerid=asreceived
callwaiting=yes
usecallingpres=yes
callwaitingcallerid=yes
threewaycalling=yes
transfer=yes
canpark=yes
cancallforward=yes
callreturn=yes
echocancel=yes
echocancelwhenbridged=yes
group=1
callgroup=1
pickupgroup=1
rxgain=0
txgain=0
hwrxgain=0
hwtxgain=3.0
sendcalleridafter =1
context=public

; Span 1: TE4/0/1 "T4XXP (PCI) Card 0 Span 1" ESF/B8ZS ClockSource
group=0,11
context=from-pstn
switchtype = national
signalling = pri_net
channel => 1-23
context = default
group = 63

; Span 2: TE4/0/2 "T4XXP (PCI) Card 0 Span 2" (MASTER) ESF/B8ZS
group=0,12
context=from-pstn
switchtype = national
signalling = pri_net
channel => 25-47
context = default
group = 63

; Span 3: TE4/0/3 "T4XXP (PCI) Card 0 Span 3" ESF/B8ZS
group=0,13
context=from-pstn
switchtype = national
signalling = pri_cpe
channel => 49-71
context = default
group = 63

; Span 4: TE4/0/4 "T4XXP (PCI) Card 0 Span 4" ESF/B8ZS
group=0,14
context=from-pstn
switchtype = national
signalling = pri_cpe
channel => 73-95
context = default
group = 63

