
[general]
bandwidth=low
disallow=lpc10
jitterbuffer=no
encryption=yes
autokill=yes

[guest]
type=user
context=public
callerid="Guest IAX User"

[iaxtel]
type=user
context=default
auth=rsa
inkeys=iaxtel

[iaxfwd]
type=user
context=default
auth=rsa
inkeys=freeworlddialup

[pbxin]
type=user
context=from-pstn

[sipPbx_0]
host=192.168.191.2
type=peer
qualify=yes
context=from-pstn

[sipPbx_1]
host=192.168.191.12
type=peer
qualify=yes
context=from-pstn

[sipPbx_2]
host=192.168.191.22
type=peer
qualify=yes
context=from-pstn

[sipPbx_3]
host=192.168.191.32
type=peer
qualify=yes
context=from-pstn

[fxoPbx_0]
host=192.168.191.4
type=peer
qualify=yes
context=from-pstn

[fxoPbx_1]
host=192.168.191.14
type=peer
qualify=yes
context=from-pstn

[fxoPbx_2]
host=192.168.191.24
type=peer
qualify=yes
context=from-pstn

[fxoPbx_3]
host=192.168.191.34
type=peer
qualify=yes
context=from-pstn

[fxsPbx_0]
host=192.168.191.5
type=peer
qualify=yes
context=from-pstn

[fxsPbx_1]
host=192.168.191.15
type=peer
qualify=yes
context=from-pstn

[fxsPbx_2]
host=192.168.191.25
type=peer
qualify=yes
context=from-pstn

[fxsPbx_3]
host=192.168.191.35
type=peer
qualify=yes
context=from-pstn

[t1sPbx_0]
host=192.168.191.3
type=peer
qualify=yes
context=from-pstn

[t1sPbx_1]
host=192.168.191.13
type=peer
qualify=yes
context=from-pstn

[t1sPbx_2]
host=192.168.191.23
type=peer
qualify=yes
context=from-pstn

[t1sPbx_3]
host=192.168.191.33
type=peer
qualify=yes
context=from-pstn

[magPbx_0]
host=192.168.191.7
type=peer
qualify=yes
context=from-pstn

[magPbx_1]
host=192.168.191.17
type=peer
qualify=yes
context=from-pstn

[magPbx_2]
host=192.168.191.27
type=peer
qualify=yes
context=from-pstn

[magPbx_3]
host=192.168.191.37
type=peer
qualify=yes
context=from-pstn

[exPbx_03]
host=192.168.191.2
type=peer
qualify=yes
context=from-pstn